/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateOrganizationDefaultVolumeBackend
 */
export interface UpdateOrganizationDefaultVolumeBackend {
    /**
     * The default volume backend for the organization. `s3fuse-legacy` mounts on the runner host using the runner’s AWS credentials (legacy behavior). `s3fuse` and `experimental` mount inside the sandbox using short-lived, bucket-scoped STS credentials.
     * @type {string}
     * @memberof UpdateOrganizationDefaultVolumeBackend
     */
    'defaultVolumeBackend': UpdateOrganizationDefaultVolumeBackendDefaultVolumeBackendEnum;
}

export const UpdateOrganizationDefaultVolumeBackendDefaultVolumeBackendEnum = {
    S3FUSE_LEGACY: 's3fuse-legacy',
    S3FUSE: 's3fuse',
    EXPERIMENTAL: 'experimental'
} as const;

export type UpdateOrganizationDefaultVolumeBackendDefaultVolumeBackendEnum = typeof UpdateOrganizationDefaultVolumeBackendDefaultVolumeBackendEnum[keyof typeof UpdateOrganizationDefaultVolumeBackendDefaultVolumeBackendEnum];


